### ISSUE TITLE
[AvatarsEverywhere] Crash on some servers

### ISSUE THREAD

**Issue by Traktool** [abUwUser/BDPlugins#15]
AvatarsEverywhere is crashing when I switch to some servers
Maybe it's caused by the recent update of 0BDFDB plugin library ?

Anyway, I've tried without AvatarsEverywhere and all works fine
I get this when I switch to a server that crash Discord

`1a7ab9c3588665635075.js:130 [Routing/Utils] transitionTo - Transitioning to /channels/903202670393839646/903202670393839649
1a7ab9c3588665635075.js:130 [Patcher] Could not fire after callback of default for AvatarsEverywhere TypeError: Cannot read property 'messageDisplayCompact' of undefined
    at Object.callback (AvatarsEverywhere.plugin.js:547)
    at Object.<anonymous> (0PluginLibrary.plugin.js:1665)
    at callOriginalMethod (0BDFDB.plugin.js:2428)
    at 0BDFDB.plugin.js:233
    at module.<computed> (0BDFDB.plugin.js:2443)
    at ua (c09ae12e36e14167ece9.js:5865)
    at $s (c09ae12e36e14167ece9.js:5917)
    at ku (c09ae12e36e14167ece9.js:5908)
    at wu (c09ae12e36e14167ece9.js:5908)
    at Uu (c09ae12e36e14167ece9.js:5908)
    at yu (c09ae12e36e14167ece9.js:5905)
    at c09ae12e36e14167ece9.js:5850
    at t.unstable_runWithPriority (c09ae12e36e14167ece9.js:6039)
    at Ki (c09ae12e36e14167ece9.js:5850)
    at qi (c09ae12e36e14167ece9.js:5850)
    at Xi (c09ae12e36e14167ece9.js:5850)
    at Ue (c09ae12e36e14167ece9.js:5927)
    at en (c09ae12e36e14167ece9.js:5827)
    at HTMLDivElement.r (1a7ab9c3588665635075.js:126)
(anonymous) @ 1a7ab9c3588665635075.js:130
t.<computed> @ c09ae12e36e14167ece9.js:4237
(anonymous) @ VM471:4
_log @ 0PluginLibrary.plugin.js:1494
err @ 0PluginLibrary.plugin.js:1450
(anonymous) @ 0PluginLibrary.plugin.js:1669
callOriginalMethod @ 0BDFDB.plugin.js:2428
(anonymous) @ 0BDFDB.plugin.js:233
module.<computed> @ 0BDFDB.plugin.js:2443
ua @ c09ae12e36e14167ece9.js:5865
$s @ c09ae12e36e14167ece9.js:5917
ku @ c09ae12e36e14167ece9.js:5908
wu @ c09ae12e36e14167ece9.js:5908
Uu @ c09ae12e36e14167ece9.js:5908
yu @ c09ae12e36e14167ece9.js:5905
(anonymous) @ c09ae12e36e14167ece9.js:5850
t.unstable_runWithPriority @ c09ae12e36e14167ece9.js:6039
Ki @ c09ae12e36e14167ece9.js:5850
qi @ c09ae12e36e14167ece9.js:5850
Xi @ c09ae12e36e14167ece9.js:5850
Ue @ c09ae12e36e14167ece9.js:5927
en @ c09ae12e36e14167ece9.js:5827
r @ 1a7ab9c3588665635075.js:126`

**Comment by ggtylerr** [comment]
Similar error, same cause. Might be a different thing though, where msg logger is conflicting.

```
fd1f7c8….js:130 [Patcher] Could not fire after callback of default for AvatarsEverywhere TypeError: Cannot read property 'messageDisplayCompact' of undefined
    at Object.callback (AvatarsEverywhere.plugin.js:547)
    at 0PluginLibrary.plugin.js:1665
    at ua (a9ae3ef….js:5870)
    at $s (a9ae3ef….js:5922)
    at ku (a9ae3ef….js:5913)
    at wu (a9ae3ef….js:5913)
    at Uu (a9ae3ef….js:5913)
    at yu (a9ae3ef….js:5910)
    at a9ae3ef….js:5855
    at t.unstable_runWithPriority (a9ae3ef….js:6044)
    at Ki (a9ae3ef….js:5855)
    at qi (a9ae3ef….js:5855)
    at Xi (a9ae3ef….js:5855)
    at Iu (a9ae3ef….js:5907)
    at Object.enqueueForceUpdate (a9ae3ef….js:5859)
    at t.h.forceUpdate (a9ae3ef….js:6014)
    at MessageLoggerV2.forceReloadMessages (MessageLoggerV2.plugin.js:3222)
    at MessageLoggerV2.patchMessages (MessageLoggerV2.plugin.js:3211)
    at MessageLoggerV2.initialize (MessageLoggerV2.plugin.js:878)
    at onLoaded (MessageLoggerV2.plugin.js:56)
    at MessageLoggerV2.start (MessageLoggerV2.plugin.js:174)
    at Object.startPlugin (<anonymous>:4:308019)
    at Object.startAddon (<anonymous>:4:307812)
    at Object.loadAddon (<anonymous>:4:268511)
    at Object.loadAddon (<anonymous>:4:305909)
    at Object.loadAllAddons (<anonymous>:4:270636)
    at Object.initialize (<anonymous>:4:265083)
    at Object.initialize (<anonymous>:4:305119)
    at Object.startup (<anonymous>:4:367198)
```

**Comment by Traktool** [comment]
> Similar error, same cause. Might be a different thing though, where msg logger is conflicting.
> 
> ```
> fd1f7c8….js:130 [Patcher] Could not fire after callback of default for AvatarsEverywhere TypeError: Cannot read property 'messageDisplayCompact' of undefined
>     at Object.callback (AvatarsEverywhere.plugin.js:547)
>     at 0PluginLibrary.plugin.js:1665
>     at ua (a9ae3ef….js:5870)
>     at $s (a9ae3ef….js:5922)
>     at ku (a9ae3ef….js:5913)
>     at wu (a9ae3ef….js:5913)
>     at Uu (a9ae3ef….js:5913)
>     at yu (a9ae3ef….js:5910)
>     at a9ae3ef….js:5855
>     at t.unstable_runWithPriority (a9ae3ef….js:6044)
>     at Ki (a9ae3ef….js:5855)
>     at qi (a9ae3ef….js:5855)
>     at Xi (a9ae3ef….js:5855)
>     at Iu (a9ae3ef….js:5907)
>     at Object.enqueueForceUpdate (a9ae3ef….js:5859)
>     at t.h.forceUpdate (a9ae3ef….js:6014)
>     at MessageLoggerV2.forceReloadMessages (MessageLoggerV2.plugin.js:3222)
>     at MessageLoggerV2.patchMessages (MessageLoggerV2.plugin.js:3211)
>     at MessageLoggerV2.initialize (MessageLoggerV2.plugin.js:878)
>     at onLoaded (MessageLoggerV2.plugin.js:56)
>     at MessageLoggerV2.start (MessageLoggerV2.plugin.js:174)
>     at Object.startPlugin (<anonymous>:4:308019)
>     at Object.startAddon (<anonymous>:4:307812)
>     at Object.loadAddon (<anonymous>:4:268511)
>     at Object.loadAddon (<anonymous>:4:305909)
>     at Object.loadAllAddons (<anonymous>:4:270636)
>     at Object.initialize (<anonymous>:4:265083)
>     at Object.initialize (<anonymous>:4:305119)
>     at Object.startup (<anonymous>:4:367198)
> ```

Without Message Logger it crash too

**Comment by Traktool** [comment]
I've tried with only libraries and AvatarsEverywhere, and it also crash

```
949b0c7f80a0ade7bad2.js:130 [Routing/Utils] transitionTo - Transitioning to /channels/903202670393839646/903202670393839649
949b0c7f80a0ade7bad2.js:130 [Patcher] Could not fire after callback of default for AvatarsEverywhere TypeError: Cannot read property 'messageDisplayCompact' of undefined
    at Object.callback (betterdiscord://plugins/AvatarsEverywhere.plugin.js:547)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1665
    at ua (f14575dc3fb26aeba3e1.js:5869)
    at $s (f14575dc3fb26aeba3e1.js:5921)
    at ku (f14575dc3fb26aeba3e1.js:5912)
    at wu (f14575dc3fb26aeba3e1.js:5912)
    at Uu (f14575dc3fb26aeba3e1.js:5912)
    at yu (f14575dc3fb26aeba3e1.js:5909)
    at f14575dc3fb26aeba3e1.js:5854
    at t.unstable_runWithPriority (f14575dc3fb26aeba3e1.js:6043)
    at Ki (f14575dc3fb26aeba3e1.js:5854)
    at qi (f14575dc3fb26aeba3e1.js:5854)
    at Xi (f14575dc3fb26aeba3e1.js:5854)
    at Ue (f14575dc3fb26aeba3e1.js:5931)
    at en (f14575dc3fb26aeba3e1.js:5831)
    at HTMLDivElement.r (949b0c7f80a0ade7bad2.js:126)
(anonymous) @ 949b0c7f80a0ade7bad2.js:130
```

**Comment by sodiboo** [comment]
I've gotten a crash recently in two separate servers when clicking on their welcome channels, so just ignoring all discussion here, it does seem to be related to putting avatars on the welcome message

**Comment by keatit71** [comment]
Having the same issue
<details>
[CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: ret.props.children.unshift is not a function
    at userName.children (betterdiscord://plugins/AvatarsEverywhere.plugin.js:622:27)
    at betterdiscord://plugins/CrashRecovery.plugin.js:364:17 
Component stack:
     at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:3344:857)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:3408:252)
    at div
    at div
    at SystemMessage
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1650:73
    at Object.freeze.r.<computed> (https://discord.com/assets/a288a5a52a0e2c8189c9.js:532:693)
    at div
    at PatchedMessageContent (betterdiscord://plugins/PreviewMessageLinks.plugin.js:432:31)
    at MessageContent
    at Ae (https://discord.com/assets/a288a5a52a0e2c8189c9.js:534:557)
    at div
    at div
    at t.default (https://discord.com/assets/f14575dc3fb26aeba3e1.js:2123:9)
    at li
    at t.default (https://discord.com/assets/f14575dc3fb26aeba3e1.js:2123:9)
    at https://discord.com/assets/3c021e87cb8bc348f71b.js:1148:15
    at ol
    at div
    at h (https://discord.com/assets/f14575dc3fb26aeba3e1.js:2134:293)
    at div
    at https://discord.com/assets/3c021e87cb8bc348f71b.js:1728:290
    at div
    at T (https://discord.com/assets/f14575dc3fb26aeba3e1.js:3949:696)
    at G (https://discord.com/assets/3c021e87cb8bc348f71b.js:1187:11)
    at main
    at Le (https://discord.com/assets/66350f4d02ae033c13ed.js:81:861)
    at https://discord.com/assets/3c021e87cb8bc348f71b.js:1740:115
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:3540:407)
    at ChatLayerProvider
    at t (https://discord.com/assets/9f2d25db83037af3e8a6.js:30:7)
    at t (https://discord.com/assets/66350f4d02ae033c13ed.js:90:12)
    at https://discord.com/assets/66350f4d02ae033c13ed.js:95:311
    at div
    at div
    at t (https://discord.com/assets/66350f4d02ae033c13ed.js:59:272)
    at e (https://discord.com/assets/4b582ee1842099625350.js:50:233)
    at https://discord.com/assets/9f2d25db83037af3e8a6.js:66:936
    at https://discord.com/assets/66350f4d02ae033c13ed.js:73:282
    at ie (https://discord.com/assets/66350f4d02ae033c13ed.js:40:591)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5987:926)
    at c (https://discord.com/assets/f14575dc3fb26aeba3e1.js:1961:867)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5990:10)
    at div
    at div
    at div
    at t.default (https://discord.com/assets/66350f4d02ae033c13ed.js:33:599)
    at div
    at l (https://discord.com/assets/f14575dc3fb26aeba3e1.js:4589:10)
    at t (https://discord.com/assets/66350f4d02ae033c13ed.js:146:803)
    at div
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:4490:162)
    at t (https://discord.com/assets/66350f4d02ae033c13ed.js:149:410)
    at Y (https://discord.com/assets/66350f4d02ae033c13ed.js:150:936)
    at div
    at t (https://discord.com/assets/66350f4d02ae033c13ed.js:245:7)
    at j (https://discord.com/assets/66350f4d02ae033c13ed.js:126:635)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5987:926)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5990:10)
    at t (https://discord.com/assets/66350f4d02ae033c13ed.js:229:880)
    at Suspense
    at d
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5987:926)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5990:10)
    at div
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:3540:407)
    at VerificationLayerProvider
    at E (https://discord.com/assets/f14575dc3fb26aeba3e1.js:2419:546)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:3540:407)
    at AppLayerProvider
    at E (https://discord.com/assets/f14575dc3fb26aeba3e1.js:1887:255)
    at h (https://discord.com/assets/f14575dc3fb26aeba3e1.js:2134:293)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:739:655)
    at I (https://discord.com/assets/f14575dc3fb26aeba3e1.js:743:113)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:743:584)
    at u (https://discord.com/assets/f14575dc3fb26aeba3e1.js:4148:738)
    at T (https://discord.com/assets/f14575dc3fb26aeba3e1.js:723:572)
    at ne (https://discord.com/assets/f14575dc3fb26aeba3e1.js:727:312)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:784:116)
    at u (https://discord.com/assets/f14575dc3fb26aeba3e1.js:4147:679)
    at https://discord.com/assets/f14575dc3fb26aeba3e1.js:4654:30
    at H (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5801:700)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5984:570)
    at t (https://discord.com/assets/f14575dc3fb26aeba3e1.js:5940:817)
    at f (https://discord.com/assets/f14575dc3fb26aeba3e1.js:2463:171)
</details>

**Comment by BigFlubba** [comment]
yeep
![image](https://user-images.githubusercontent.com/69104450/171536856-c87c12d2-9265-4a28-b211-57d410fb58bb.png)

**Comment by Synaptic149** [comment]
I got this issue when opening a private channel I have access to. It probably crashes when you go to certain servers because the last channel you had open on your client on that server was a private channel.

**Comment by Synaptic149** [comment]
I also get this when I check its settings
![image](https://user-images.githubusercontent.com/59460385/172027641-17ba38a0-bb44-4974-bdc4-443d36764841.png)
