### ISSUE TITLE
[Avatars Everywhere] Plugin could not be compiled

### ISSUE THREAD

**Issue by jogerj** [abUwUser/BDPlugins#18]
Seems to be an issue affecting many plugins due to some changes to latest discord update. 
BetterDiscord 1.6.0

<details>
<summary>log output</summary>

```
<html>
<body>
<!--StartFragment-->

TypeError: Cannot read property 'register' of undefined
--
2 | at new e (https://discord.com/assets/998d03874151e82d569a.js:4287:740)
3 | at new SettingsManager (betterdiscord://plugins/AvatarsEverywhere.plugin.js:349:7)
4 | at Object.166 (betterdiscord://plugins/AvatarsEverywhere.plugin.js:364:22)
5 | at __webpack_require__ (betterdiscord://plugins/AvatarsEverywhere.plugin.js:752:33)
6 | at eval (betterdiscord://plugins/AvatarsEverywhere.plugin.js:786:29)
7 | at buildPlugin (betterdiscord://plugins/AvatarsEverywhere.plugin.js:788:4)
8 | at eval (betterdiscord://plugins/AvatarsEverywhere.plugin.js:793:2)
9 | at Object.requireAddon (<anonymous>:4:43432)
10 | at Object.loadAddon (<anonymous>:4:9220)
11 | at Object.loadAddon (<anonymous>:4:41184)
12 | at Object.updateList (<anonymous>:4:11085)
13 | at Object.updatePluginList (<anonymous>:4:40881)
14 | at O.reload (<anonymous>:4:109713)
15 | at Object.Ye (https://discord.com/assets/998d03874151e82d569a.js:5981:658)
16 | at qe (https://discord.com/assets/998d03874151e82d569a.js:5981:812)
17 | at https://discord.com/assets/998d03874151e82d569a.js:6001:409
18 | at Pr (https://discord.com/assets/998d03874151e82d569a.js:6001:506)
19 | at Mr (https://discord.com/assets/998d03874151e82d569a.js:6001:920)
20 | at https://discord.com/assets/998d03874151e82d569a.js:6007:680
21 | at ke (https://discord.com/assets/998d03874151e82d569a.js:6089:404)
22 | at https://discord.com/assets/998d03874151e82d569a.js:6003:395
23 | at Vr (https://discord.com/assets/998d03874151e82d569a.js:6003:425)
24 | at rn (https://discord.com/assets/998d03874151e82d569a.js:5990:757)
25 | at nn (https://discord.com/assets/998d03874151e82d569a.js:5990:7)
26 | at t.unstable_runWithPriority (https://discord.com/assets/998d03874151e82d569a.js:6201:828)
27 | at Ki (https://discord.com/assets/998d03874151e82d569a.js:6012:117)
28 | at Ue (https://discord.com/assets/998d03874151e82d569a.js:6089:144)
29 | at en (https://discord.com/assets/998d03874151e82d569a.js:5989:800)
30 | at HTMLDivElement.r (https://discord.com/assets/375fb6bbb55063d1f9db.js:126:559)

<!--EndFragment-->
</body>
</html>
```

</details>

**Comment by nexioss** [comment]
same here
but i have missing start or stop fonction. instead

**Comment by Styphoryte** [comment]
Same issue unfortunately and I cannot find any alternatives to this plugin.

log output

```
<html>
<body>
<!--StartFragment-->

TypeError: Cannot read property 'register' of undefined
--
2 | at new e (https://discord.com/assets/998d03874151e82d569a.js:4287:740)
3 | at new SettingsManager (betterdiscord://plugins/AvatarsEverywhere.plugin.js:349:7)
4 | at Object.166 (betterdiscord://plugins/AvatarsEverywhere.plugin.js:364:22)
5 | at __webpack_require__ (betterdiscord://plugins/AvatarsEverywhere.plugin.js:752:33)
6 | at eval (betterdiscord://plugins/AvatarsEverywhere.plugin.js:786:29)
7 | at buildPlugin (betterdiscord://plugins/AvatarsEverywhere.plugin.js:788:4)
8 | at eval (betterdiscord://plugins/AvatarsEverywhere.plugin.js:793:2)
9 | at Object.requireAddon (<anonymous>:4:43432)
10 | at Object.loadAddon (<anonymous>:4:9220)
11 | at Object.loadAddon (<anonymous>:4:41184)
12 | at Object.updateList (<anonymous>:4:11085)
13 | at Object.updatePluginList (<anonymous>:4:40881)
14 | at O.reload (<anonymous>:4:109713)
15 | at Object.Ye (https://discord.com/assets/998d03874151e82d569a.js:5981:658)
16 | at qe (https://discord.com/assets/998d03874151e82d569a.js:5981:812)
17 | at https://discord.com/assets/998d03874151e82d569a.js:6001:409
18 | at Pr (https://discord.com/assets/998d03874151e82d569a.js:6001:506)
19 | at Mr (https://discord.com/assets/998d03874151e82d569a.js:6001:920)
20 | at https://discord.com/assets/998d03874151e82d569a.js:6007:680
21 | at ke (https://discord.com/assets/998d03874151e82d569a.js:6089:404)
22 | at https://discord.com/assets/998d03874151e82d569a.js:6003:395
23 | at Vr (https://discord.com/assets/998d03874151e82d569a.js:6003:425)
24 | at rn (https://discord.com/assets/998d03874151e82d569a.js:5990:757)
25 | at nn (https://discord.com/assets/998d03874151e82d569a.js:5990:7)
26 | at t.unstable_runWithPriority (https://discord.com/assets/998d03874151e82d569a.js:6201:828)
27 | at Ki (https://discord.com/assets/998d03874151e82d569a.js:6012:117)
28 | at Ue (https://discord.com/assets/998d03874151e82d569a.js:6089:144)
29 | at en (https://discord.com/assets/998d03874151e82d569a.js:5989:800)
30 | at HTMLDivElement.r (https://discord.com/assets/375fb6bbb55063d1f9db.js:126:559)

<!--EndFragment-->
</body>
</html>
```
